import Head from 'next/head'
import { signIn } from "next-auth/react"
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Who pays me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Who pays me</h1>

        <p>Keep track of whom is in debit with you.</p>

        <a onClick={() => signIn(null, { callbackUrl: 'http://localhost:3000/dashboard' })}>Login</a>
        
      </main>

      <footer className={styles.footer}>
        Made by <a href="https://github.com/ViniciusTei">ViniciusTei</a>
      </footer>
    </div>
  )
}
